### PR TITLE
Added support for alt text to the underlying html <img> element.

### PR DESCRIPTION
**Pull request by JoelVenable**

### CODE REVIEW

**Comment by leMaik** [comment]
Since all undocumented props are passed through to the underlying image, this is already possible with `alt="your alt text"`. :thinking:

**Comment by JoelVenable** [comment]
Ok, good to know.  Might be worth mentioning in the docs.  Helps those still learning React like myself.

**Comment by leMaik** [comment]
@JoelVenable Would you like to create a PR that adds something like "All other props are passed through to the underlying `img` tag."?

**Comment by JoelVenable** [comment]
Sure thing.  I also just realized that introducing a new prop and marking it as required would constitute a breaking change.  😄

**Comment by leMaik** [comment]
@JoelVenable Indeed, it shouldn't be required, but when not required, it would be a minor semver change.

**Pull request closed without merging**
